import Head from 'next/head'
import Hero from '@/components/Hero'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <Hero
          mainTitle='Health, Safety and Environmental'
          subtitle='Optional text lorem ipsum dolor sit amet consectetur elit on 2 lines.'
          imagePosition='full'
          imageSet={{url: 'https://via.placeholder.com/1440x552', alt: 'mon image'}}
          category='Category'
          date='01/10/2019'
          sectionTitle='Section blurb lorem ipsum dolor sit amet consectectur adipiscing elit.'
          textScroll="Scroll down for more"
          links={[
            {
              title: 'test',
              uri: 'http://www.google.com',
            },
            {
              title: 'test',
              uri: 'http://www.google.com',
            },
            {
              title: 'test',
              uri: 'http://www.google.com',
            },
          ]}
        />
      </main>
    </>
  )
}
